export default {
  id: "aqua-tide",
  name: "Aqua Tide",
  description: "Oceanic glass — deep teal blues with flowing aqua light.",
  tags: ["glass","blue","ocean"],
  preview: {"bg":"#F0FDFA","a":"#0EA5E9","b":"#22D3EE","c":"#F59E0B"},
  tokens: {
    primary: "#0EA5E9",
    primaryFg: "#FFFFFF",
    secondary: "#22D3EE",
    accent: "#F59E0B",
    bg: "#F0FDFA",
    surface: "#FFFFFF",
    surfaceAlt: "#ECFEFF",
    text: "#0C2B33",
    textMuted: "#5B7C86",
    border: "#BDE7F2",
    success: "#10B981",
    warning: "#F59E0B",
    danger: "#EF4444",
    info: "#3B82F6",
    fontHeading: "'Inter', system-ui, sans-serif",
    fontBody: "'Inter', system-ui, sans-serif",
    baseSize: 15,
    scaleRatio: 1.25,
    headingWeight: "700",
    bodyWeight: "400",
    lineHeight: 1.55,
    letterSpacing: -0.2,
    headingCase: "none",
    radius: 18,
    radiusSm: 10,
    borderWidth: 1,
    shadowIntensity: "soft",
    containerWidth: 1280,
    sectionGap: 64,
    gridGap: 16,
    cardStyle: "glass",
    buttonStyle: "solid",
    inputStyle: "outlined",
    imageRatio: "16/9",
    plpColumns: 4,
    intensity: "normal",
    pageTransition: "fade",
    hoverLift: true,
    parallax: true,
    confetti: false,
    backgroundFx: "aurora",
    scrollReveal: true,
    duration: 1,
  },
}
