export default {
  id: "arctic-white",
  name: "Arctic White",
  description: "Clinical calm — pure white, glacial blue accents, whisper-soft motion.",
  tags: ["light","minimal","white","calm"],
  preview: {"bg":"#FFFFFF","a":"#0284C7","b":"#7DD3FC","c":"#0EA5E9"},
  tokens: {
    primary: "#0284C7",
    primaryFg: "#FFFFFF",
    secondary: "#7DD3FC",
    accent: "#0EA5E9",
    bg: "#FFFFFF",
    surface: "#FFFFFF",
    surfaceAlt: "#F8FAFC",
    text: "#0F172A",
    textMuted: "#94A3B8",
    border: "#E8EEF4",
    success: "#10B981",
    warning: "#F59E0B",
    danger: "#EF4444",
    info: "#3B82F6",
    fontHeading: "'Inter', system-ui, sans-serif",
    fontBody: "'Inter', system-ui, sans-serif",
    baseSize: 15,
    scaleRatio: 1.25,
    headingWeight: "600",
    bodyWeight: "400",
    lineHeight: 1.55,
    letterSpacing: -0.2,
    headingCase: "none",
    radius: 12,
    radiusSm: 8,
    borderWidth: 1,
    shadowIntensity: "none",
    containerWidth: 1280,
    sectionGap: 64,
    gridGap: 16,
    cardStyle: "outlined",
    buttonStyle: "solid",
    inputStyle: "outlined",
    imageRatio: "3/4",
    plpColumns: 4,
    intensity: "subtle",
    pageTransition: "fade",
    hoverLift: true,
    parallax: true,
    confetti: false,
    backgroundFx: "none",
    scrollReveal: true,
    duration: 1.2,
  },
}
