export default {
  id: "art-deco-gold",
  name: "Art Deco Gold",
  description: "Gatsby glamour — geometric gold lines on black lacquer.",
  tags: ["dark","retro","gold","luxury"],
  preview: {"bg":"#0F0D08","a":"#D4AF37","b":"#8C6D1F","c":"#F5E6C4"},
  tokens: {
    primary: "#D4AF37",
    primaryFg: "#0F0D08",
    secondary: "#8C6D1F",
    accent: "#F5E6C4",
    bg: "#0F0D08",
    surface: "#171310",
    surfaceAlt: "#130F0B",
    text: "#F5EFE0",
    textMuted: "#A89A7C",
    border: "#3A2F1D",
    success: "#10B981",
    warning: "#F59E0B",
    danger: "#EF4444",
    info: "#3B82F6",
    fontHeading: "'Playfair Display', Georgia, serif",
    fontBody: "'Inter', system-ui, sans-serif",
    baseSize: 15,
    scaleRatio: 1.25,
    headingWeight: "800",
    bodyWeight: "400",
    lineHeight: 1.55,
    letterSpacing: 2,
    headingCase: "uppercase",
    radius: 4,
    radiusSm: 2,
    borderWidth: 1,
    shadowIntensity: "none",
    containerWidth: 1280,
    sectionGap: 64,
    gridGap: 16,
    cardStyle: "outlined",
    buttonStyle: "solid",
    inputStyle: "outlined",
    imageRatio: "4/5",
    plpColumns: 4,
    intensity: "subtle",
    pageTransition: "fade",
    hoverLift: true,
    parallax: true,
    confetti: false,
    backgroundFx: "none",
    scrollReveal: true,
    duration: 1,
  },
}
