export default {
  id: "atelier-cream",
  name: "Atelier Cream",
  description: "Couture atelier — warm cream, ink, and champagne serif elegance.",
  tags: ["light","fashion","elegant"],
  preview: {"bg":"#F7F3EC","a":"#1A1A1A","b":"#8A6D3B","c":"#C9A96A"},
  tokens: {
    primary: "#1A1A1A",
    primaryFg: "#FFFFFF",
    secondary: "#8A6D3B",
    accent: "#C9A96A",
    bg: "#F7F3EC",
    surface: "#FFFDF8",
    surfaceAlt: "#F1EAD9",
    text: "#1A1A1A",
    textMuted: "#8C8272",
    border: "#E3D9C2",
    success: "#10B981",
    warning: "#F59E0B",
    danger: "#EF4444",
    info: "#3B82F6",
    fontHeading: "'Playfair Display', Georgia, serif",
    fontBody: "Georgia, 'Times New Roman', serif",
    baseSize: 15,
    scaleRatio: 1.25,
    headingWeight: "700",
    bodyWeight: "400",
    lineHeight: 1.55,
    letterSpacing: 0.3,
    headingCase: "capitalize",
    radius: 4,
    radiusSm: 2,
    borderWidth: 1,
    shadowIntensity: "soft",
    containerWidth: 1280,
    sectionGap: 96,
    gridGap: 16,
    cardStyle: "raised",
    buttonStyle: "solid",
    inputStyle: "outlined",
    imageRatio: "4/5",
    plpColumns: 3,
    intensity: "subtle",
    pageTransition: "fade",
    hoverLift: true,
    parallax: true,
    confetti: false,
    backgroundFx: "none",
    scrollReveal: true,
    duration: 1,
  },
}
