export default {
  id: "autumn-harvest",
  name: "Autumn Harvest",
  description: "Falling-leaves warmth — burnt orange, ochre and olive.",
  tags: ["seasonal","autumn","warm","earthy"],
  preview: {"bg":"#FDF6ED","a":"#C2410C","b":"#A16207","c":"#65A30D"},
  tokens: {
    primary: "#C2410C",
    primaryFg: "#FFFFFF",
    secondary: "#A16207",
    accent: "#65A30D",
    bg: "#FDF6ED",
    surface: "#FFFDF7",
    surfaceAlt: "#F6E8D2",
    text: "#3A2412",
    textMuted: "#A07E52",
    border: "#E8D2AC",
    success: "#10B981",
    warning: "#F59E0B",
    danger: "#EF4444",
    info: "#3B82F6",
    fontHeading: "Georgia, 'Times New Roman', serif",
    fontBody: "'Inter', system-ui, sans-serif",
    baseSize: 15,
    scaleRatio: 1.25,
    headingWeight: "700",
    bodyWeight: "400",
    lineHeight: 1.55,
    letterSpacing: 0,
    headingCase: "none",
    radius: 14,
    radiusSm: 8,
    borderWidth: 1,
    shadowIntensity: "medium",
    containerWidth: 1280,
    sectionGap: 64,
    gridGap: 16,
    cardStyle: "raised",
    buttonStyle: "solid",
    inputStyle: "outlined",
    imageRatio: "4/5",
    plpColumns: 4,
    intensity: "subtle",
    pageTransition: "fade",
    hoverLift: true,
    parallax: true,
    confetti: false,
    backgroundFx: "none",
    scrollReveal: true,
    duration: 1,
  },
}
