export default {
  id: "bakery-warm",
  name: "Bakery Warm",
  description: "Fresh-from-oven — caramel, cherry and cream with soft round warmth.",
  tags: ["food","bakery","warm"],
  preview: {"bg":"#FDF6EC","a":"#B45309","b":"#92400E","c":"#DC2626"},
  tokens: {
    primary: "#B45309",
    primaryFg: "#FFFFFF",
    secondary: "#92400E",
    accent: "#DC2626",
    bg: "#FDF6EC",
    surface: "#FFFDF6",
    surfaceAlt: "#F7EBD3",
    text: "#3B2410",
    textMuted: "#A08059",
    border: "#EBD6B4",
    success: "#10B981",
    warning: "#F59E0B",
    danger: "#EF4444",
    info: "#3B82F6",
    fontHeading: "Georgia, 'Times New Roman', serif",
    fontBody: "'Inter', system-ui, sans-serif",
    baseSize: 15,
    scaleRatio: 1.25,
    headingWeight: "700",
    bodyWeight: "400",
    lineHeight: 1.55,
    letterSpacing: 0,
    headingCase: "none",
    radius: 20,
    radiusSm: 12,
    borderWidth: 1,
    shadowIntensity: "soft",
    containerWidth: 1280,
    sectionGap: 64,
    gridGap: 16,
    cardStyle: "raised",
    buttonStyle: "pill",
    inputStyle: "outlined",
    imageRatio: "1/1",
    plpColumns: 4,
    intensity: "subtle",
    pageTransition: "fade",
    hoverLift: true,
    parallax: true,
    confetti: false,
    backgroundFx: "none",
    scrollReveal: true,
    duration: 1,
  },
}
