export default {
  id: "banarasi-silk",
  name: "Banarasi Silk",
  description: "Regal maroon silk — deep wine with woven gold zari light.",
  tags: ["dark","indian","luxury","silk"],
  preview: {"bg":"#2A0A12","a":"#F59E0B","b":"#DC2626","c":"#FBBF24"},
  tokens: {
    primary: "#F59E0B",
    primaryFg: "#2A0A12",
    secondary: "#DC2626",
    accent: "#FBBF24",
    bg: "#2A0A12",
    surface: "#3A0F18",
    surfaceAlt: "#330D16",
    text: "#FDF2E9",
    textMuted: "#C9A68F",
    border: "#5A2430",
    success: "#10B981",
    warning: "#F59E0B",
    danger: "#EF4444",
    info: "#3B82F6",
    fontHeading: "'Playfair Display', Georgia, serif",
    fontBody: "'Inter', system-ui, sans-serif",
    baseSize: 15,
    scaleRatio: 1.25,
    headingWeight: "800",
    bodyWeight: "400",
    lineHeight: 1.55,
    letterSpacing: 0.4,
    headingCase: "none",
    radius: 10,
    radiusSm: 6,
    borderWidth: 1,
    shadowIntensity: "strong",
    containerWidth: 1280,
    sectionGap: 64,
    gridGap: 16,
    cardStyle: "raised",
    buttonStyle: "solid",
    inputStyle: "outlined",
    imageRatio: "4/5",
    plpColumns: 4,
    intensity: "subtle",
    pageTransition: "fade",
    hoverLift: true,
    parallax: true,
    confetti: false,
    backgroundFx: "rangoli",
    scrollReveal: true,
    duration: 1,
  },
}
