export default {
  id: "bare-stone",
  name: "Bare Stone",
  description: "Raw minimalism — honest stone greys on a soft concrete ground.",
  tags: ["light","minimal","grey"],
  preview: {"bg":"#EDEBE8","a":"#44403C","b":"#78716C","c":"#B45309"},
  tokens: {
    primary: "#44403C",
    primaryFg: "#FFFFFF",
    secondary: "#78716C",
    accent: "#B45309",
    bg: "#EDEBE8",
    surface: "#F7F5F3",
    surfaceAlt: "#E4E1DD",
    text: "#292524",
    textMuted: "#8A8580",
    border: "#D6D1CB",
    success: "#10B981",
    warning: "#F59E0B",
    danger: "#EF4444",
    info: "#3B82F6",
    fontHeading: "'Inter', system-ui, sans-serif",
    fontBody: "'Inter', system-ui, sans-serif",
    baseSize: 15,
    scaleRatio: 1.25,
    headingWeight: "600",
    bodyWeight: "400",
    lineHeight: 1.55,
    letterSpacing: -0.2,
    headingCase: "none",
    radius: 6,
    radiusSm: 4,
    borderWidth: 1,
    shadowIntensity: "none",
    containerWidth: 1280,
    sectionGap: 64,
    gridGap: 16,
    cardStyle: "flat",
    buttonStyle: "solid",
    inputStyle: "outlined",
    imageRatio: "3/4",
    plpColumns: 4,
    intensity: "off",
    pageTransition: "none",
    hoverLift: true,
    parallax: true,
    confetti: false,
    backgroundFx: "noise",
    scrollReveal: true,
    duration: 1,
  },
}
