export default {
  id: "bubblegum-pop",
  name: "Bubblegum Pop",
  description: "Chewy and fun — bubblegum pink, violet fizz and sky pop.",
  tags: ["kids","playful","pink","fun"],
  preview: {"bg":"#FDF2F8","a":"#F472B6","b":"#A855F7","c":"#38BDF8"},
  tokens: {
    primary: "#F472B6",
    primaryFg: "#FFFFFF",
    secondary: "#A855F7",
    accent: "#38BDF8",
    bg: "#FDF2F8",
    surface: "#FFFFFF",
    surfaceAlt: "#F9E2F0",
    text: "#4A1440",
    textMuted: "#B07AA5",
    border: "#F3C4E3",
    success: "#10B981",
    warning: "#F59E0B",
    danger: "#EF4444",
    info: "#3B82F6",
    fontHeading: "'Poppins', 'Inter', system-ui, sans-serif",
    fontBody: "'Poppins', 'Inter', system-ui, sans-serif",
    baseSize: 15,
    scaleRatio: 1.25,
    headingWeight: "800",
    bodyWeight: "400",
    lineHeight: 1.55,
    letterSpacing: 0,
    headingCase: "capitalize",
    radius: 24,
    radiusSm: 16,
    borderWidth: 1,
    shadowIntensity: "soft",
    containerWidth: 1280,
    sectionGap: 64,
    gridGap: 16,
    cardStyle: "raised",
    buttonStyle: "pill",
    inputStyle: "outlined",
    imageRatio: "1/1",
    plpColumns: 4,
    intensity: "normal",
    pageTransition: "scale",
    hoverLift: true,
    parallax: true,
    confetti: true,
    backgroundFx: "none",
    scrollReveal: true,
    duration: 1,
  },
}
