export default {
  id: "candy-pop",
  name: "Candy Pop",
  description: "Sugar-rush storefront — candy pink, grape and lemon with confetti.",
  tags: ["kids","playful","pink"],
  preview: {"bg":"#FFF7FB","a":"#EC4899","b":"#8B5CF6","c":"#FBBF24"},
  tokens: {
    primary: "#EC4899",
    primaryFg: "#FFFFFF",
    secondary: "#8B5CF6",
    accent: "#FBBF24",
    bg: "#FFF7FB",
    surface: "#FFFFFF",
    surfaceAlt: "#FCE7F3",
    text: "#4A1030",
    textMuted: "#B0769A",
    border: "#F6C6E2",
    success: "#10B981",
    warning: "#F59E0B",
    danger: "#EF4444",
    info: "#3B82F6",
    fontHeading: "'Poppins', 'Inter', system-ui, sans-serif",
    fontBody: "'Poppins', 'Inter', system-ui, sans-serif",
    baseSize: 15,
    scaleRatio: 1.25,
    headingWeight: "800",
    bodyWeight: "400",
    lineHeight: 1.55,
    letterSpacing: 0,
    headingCase: "none",
    radius: 24,
    radiusSm: 16,
    borderWidth: 1,
    shadowIntensity: "medium",
    containerWidth: 1280,
    sectionGap: 64,
    gridGap: 16,
    cardStyle: "raised",
    buttonStyle: "pill",
    inputStyle: "outlined",
    imageRatio: "1/1",
    plpColumns: 4,
    intensity: "normal",
    pageTransition: "scale",
    hoverLift: true,
    parallax: true,
    confetti: true,
    backgroundFx: "none",
    scrollReveal: true,
    duration: 1,
  },
}
