export default {
  id: "carbon-luxe",
  name: "Carbon Luxe",
  description: "Industrial luxury — carbon dark with amber precision highlights.",
  tags: ["dark","luxury","industrial"],
  preview: {"bg":"#111214","a":"#FBBF24","b":"#F97316","c":"#E2E8F0"},
  tokens: {
    primary: "#FBBF24",
    primaryFg: "#111214",
    secondary: "#F97316",
    accent: "#E2E8F0",
    bg: "#111214",
    surface: "#1A1C1E",
    surfaceAlt: "#17191B",
    text: "#F8FAFC",
    textMuted: "#9AA1AB",
    border: "#2B2F33",
    success: "#10B981",
    warning: "#F59E0B",
    danger: "#EF4444",
    info: "#3B82F6",
    fontHeading: "'Inter', system-ui, sans-serif",
    fontBody: "'Inter', system-ui, sans-serif",
    baseSize: 15,
    scaleRatio: 1.25,
    headingWeight: "800",
    bodyWeight: "400",
    lineHeight: 1.55,
    letterSpacing: 1,
    headingCase: "uppercase",
    radius: 8,
    radiusSm: 4,
    borderWidth: 1,
    shadowIntensity: "medium",
    containerWidth: 1280,
    sectionGap: 64,
    gridGap: 16,
    cardStyle: "raised",
    buttonStyle: "solid",
    inputStyle: "filled",
    imageRatio: "3/4",
    plpColumns: 4,
    intensity: "normal",
    pageTransition: "fade",
    hoverLift: true,
    parallax: true,
    confetti: false,
    backgroundFx: "grid",
    scrollReveal: true,
    duration: 1,
  },
}
