export default {
  id: "champagne-pearl",
  name: "Champagne Pearl",
  description: "Understated bridal — champagne, pearl and soft gold line-work.",
  tags: ["light","jewellery","elegant"],
  preview: {"bg":"#FBF7F0","a":"#B08D57","b":"#8A7B66","c":"#E7C873"},
  tokens: {
    primary: "#B08D57",
    primaryFg: "#FFFFFF",
    secondary: "#8A7B66",
    accent: "#E7C873",
    bg: "#FBF7F0",
    surface: "#FFFDF9",
    surfaceAlt: "#F3EAD9",
    text: "#2E2820",
    textMuted: "#9A8C76",
    border: "#E5D6B8",
    success: "#10B981",
    warning: "#F59E0B",
    danger: "#EF4444",
    info: "#3B82F6",
    fontHeading: "'Playfair Display', Georgia, serif",
    fontBody: "Georgia, 'Times New Roman', serif",
    baseSize: 15,
    scaleRatio: 1.25,
    headingWeight: "600",
    bodyWeight: "400",
    lineHeight: 1.55,
    letterSpacing: 0.5,
    headingCase: "none",
    radius: 24,
    radiusSm: 14,
    borderWidth: 1,
    shadowIntensity: "soft",
    containerWidth: 1280,
    sectionGap: 96,
    gridGap: 16,
    cardStyle: "outlined",
    buttonStyle: "solid",
    inputStyle: "outlined",
    imageRatio: "1/1",
    plpColumns: 3,
    intensity: "subtle",
    pageTransition: "fade",
    hoverLift: true,
    parallax: true,
    confetti: false,
    backgroundFx: "none",
    scrollReveal: true,
    duration: 1,
  },
}
