export default {
  id: "citrus-zest",
  name: "Citrus Zest",
  description: "Zingy and bright — orange, lemon and lime with snappy motion.",
  tags: ["food","fresh","citrus","playful"],
  preview: {"bg":"#FFFDE7","a":"#F97316","b":"#EAB308","c":"#16A34A"},
  tokens: {
    primary: "#F97316",
    primaryFg: "#FFFFFF",
    secondary: "#EAB308",
    accent: "#16A34A",
    bg: "#FFFDE7",
    surface: "#FFFFFF",
    surfaceAlt: "#FEF9DC",
    text: "#422006",
    textMuted: "#A3854A",
    border: "#F5E3A8",
    success: "#10B981",
    warning: "#F59E0B",
    danger: "#EF4444",
    info: "#3B82F6",
    fontHeading: "'Inter', system-ui, sans-serif",
    fontBody: "'Inter', system-ui, sans-serif",
    baseSize: 15,
    scaleRatio: 1.25,
    headingWeight: "800",
    bodyWeight: "400",
    lineHeight: 1.55,
    letterSpacing: 0,
    headingCase: "none",
    radius: 18,
    radiusSm: 10,
    borderWidth: 1,
    shadowIntensity: "medium",
    containerWidth: 1280,
    sectionGap: 64,
    gridGap: 16,
    cardStyle: "raised",
    buttonStyle: "pill",
    inputStyle: "outlined",
    imageRatio: "1/1",
    plpColumns: 4,
    intensity: "normal",
    pageTransition: "slide",
    hoverLift: true,
    parallax: true,
    confetti: false,
    backgroundFx: "none",
    scrollReveal: true,
    duration: 1,
  },
}
