export default {
  id: "clay-sage",
  name: "Clay & Sage",
  description: "Artisan pottery — warm clay and garden sage on linen.",
  tags: ["light","nature","craft","earthy"],
  preview: {"bg":"#F7F5F0","a":"#B45309","b":"#84A98C","c":"#6B7280"},
  tokens: {
    primary: "#B45309",
    primaryFg: "#FFFFFF",
    secondary: "#84A98C",
    accent: "#6B7280",
    bg: "#F7F5F0",
    surface: "#FFFDF8",
    surfaceAlt: "#EEE9DC",
    text: "#292524",
    textMuted: "#8A8078",
    border: "#DED5C2",
    success: "#10B981",
    warning: "#F59E0B",
    danger: "#EF4444",
    info: "#3B82F6",
    fontHeading: "Georgia, 'Times New Roman', serif",
    fontBody: "'Inter', system-ui, sans-serif",
    baseSize: 15,
    scaleRatio: 1.25,
    headingWeight: "600",
    bodyWeight: "400",
    lineHeight: 1.55,
    letterSpacing: 0,
    headingCase: "none",
    radius: 16,
    radiusSm: 10,
    borderWidth: 1,
    shadowIntensity: "soft",
    containerWidth: 1280,
    sectionGap: 64,
    gridGap: 16,
    cardStyle: "raised",
    buttonStyle: "solid",
    inputStyle: "outlined",
    imageRatio: "3/4",
    plpColumns: 4,
    intensity: "subtle",
    pageTransition: "fade",
    hoverLift: true,
    parallax: true,
    confetti: false,
    backgroundFx: "noise",
    scrollReveal: true,
    duration: 1,
  },
}
