export default {
  id: "crystal-rose",
  name: "Crystal Rose",
  description: "Rosy frosted glass — blush gradients and translucent rose panels.",
  tags: ["light","glass","pink","romantic"],
  preview: {"bg":"#FDF2F8","a":"#EC4899","b":"#F472B6","c":"#8B5CF6"},
  tokens: {
    primary: "#EC4899",
    primaryFg: "#FFFFFF",
    secondary: "#F472B6",
    accent: "#8B5CF6",
    bg: "#FDF2F8",
    surface: "#FFFFFF",
    surfaceAlt: "#FCE7F3",
    text: "#3B1D2E",
    textMuted: "#A0758F",
    border: "#F5D0E4",
    success: "#10B981",
    warning: "#F59E0B",
    danger: "#EF4444",
    info: "#3B82F6",
    fontHeading: "'Inter', system-ui, sans-serif",
    fontBody: "'Inter', system-ui, sans-serif",
    baseSize: 15,
    scaleRatio: 1.25,
    headingWeight: "600",
    bodyWeight: "400",
    lineHeight: 1.55,
    letterSpacing: -0.2,
    headingCase: "none",
    radius: 22,
    radiusSm: 12,
    borderWidth: 1,
    shadowIntensity: "soft",
    containerWidth: 1280,
    sectionGap: 64,
    gridGap: 16,
    cardStyle: "glass",
    buttonStyle: "solid",
    inputStyle: "outlined",
    imageRatio: "3/4",
    plpColumns: 4,
    intensity: "cinematic",
    pageTransition: "fade",
    hoverLift: true,
    parallax: true,
    confetti: false,
    backgroundFx: "aurora",
    scrollReveal: true,
    duration: 1,
  },
}
