export default {
  id: "deep-space",
  name: "Deep Space",
  description: "Cosmic commerce — violet nebula and starlight on void black.",
  tags: ["dark","tech","space"],
  preview: {"bg":"#030014","a":"#7C3AED","b":"#2563EB","c":"#22D3EE"},
  tokens: {
    primary: "#7C3AED",
    primaryFg: "#FFFFFF",
    secondary: "#2563EB",
    accent: "#22D3EE",
    bg: "#030014",
    surface: "#0C0628",
    surfaceAlt: "#08041E",
    text: "#EDE9FE",
    textMuted: "#9B93C9",
    border: "#2A1D5E",
    success: "#10B981",
    warning: "#F59E0B",
    danger: "#EF4444",
    info: "#3B82F6",
    fontHeading: "'Inter', system-ui, sans-serif",
    fontBody: "'Inter', system-ui, sans-serif",
    baseSize: 15,
    scaleRatio: 1.25,
    headingWeight: "800",
    bodyWeight: "400",
    lineHeight: 1.55,
    letterSpacing: -0.2,
    headingCase: "none",
    radius: 18,
    radiusSm: 10,
    borderWidth: 1,
    shadowIntensity: "strong",
    containerWidth: 1280,
    sectionGap: 64,
    gridGap: 16,
    cardStyle: "glass",
    buttonStyle: "solid",
    inputStyle: "outlined",
    imageRatio: "3/4",
    plpColumns: 4,
    intensity: "cinematic",
    pageTransition: "blur",
    hoverLift: true,
    parallax: true,
    confetti: false,
    backgroundFx: "mesh",
    scrollReveal: true,
    duration: 1,
  },
}
