export default {
  id: "desert-dune",
  name: "Desert Dune",
  description: "Sun-baked calm — sand, clay and stone in quiet balance.",
  tags: ["light","nature","earthy","minimal"],
  preview: {"bg":"#FAF3E7","a":"#B45309","b":"#D97706","c":"#78716C"},
  tokens: {
    primary: "#B45309",
    primaryFg: "#FFFFFF",
    secondary: "#D97706",
    accent: "#78716C",
    bg: "#FAF3E7",
    surface: "#FFFDF6",
    surfaceAlt: "#F1E5CE",
    text: "#3A2A18",
    textMuted: "#A08B6B",
    border: "#E4D3B3",
    success: "#10B981",
    warning: "#F59E0B",
    danger: "#EF4444",
    info: "#3B82F6",
    fontHeading: "Georgia, 'Times New Roman', serif",
    fontBody: "'Inter', system-ui, sans-serif",
    baseSize: 15,
    scaleRatio: 1.25,
    headingWeight: "600",
    bodyWeight: "400",
    lineHeight: 1.55,
    letterSpacing: 0.2,
    headingCase: "none",
    radius: 6,
    radiusSm: 4,
    borderWidth: 1,
    shadowIntensity: "none",
    containerWidth: 1280,
    sectionGap: 96,
    gridGap: 16,
    cardStyle: "flat",
    buttonStyle: "solid",
    inputStyle: "outlined",
    imageRatio: "3/4",
    plpColumns: 4,
    intensity: "off",
    pageTransition: "fade",
    hoverLift: true,
    parallax: true,
    confetti: false,
    backgroundFx: "noise",
    scrollReveal: true,
    duration: 1,
  },
}
