export default {
  id: "diwali-glow",
  name: "Diwali Glow",
  description: "Festival of lights — glowing gold and diya flame on midnight warmth.",
  tags: ["dark","festive","indian","gold"],
  preview: {"bg":"#1C0F08","a":"#FBBF24","b":"#F97316","c":"#EF4444"},
  tokens: {
    primary: "#FBBF24",
    primaryFg: "#1C0F08",
    secondary: "#F97316",
    accent: "#EF4444",
    bg: "#1C0F08",
    surface: "#2A1709",
    surfaceAlt: "#241306",
    text: "#FEF3E2",
    textMuted: "#C9A87F",
    border: "#4A2E15",
    success: "#10B981",
    warning: "#F59E0B",
    danger: "#EF4444",
    info: "#3B82F6",
    fontHeading: "'Playfair Display', Georgia, serif",
    fontBody: "'Inter', system-ui, sans-serif",
    baseSize: 15,
    scaleRatio: 1.25,
    headingWeight: "800",
    bodyWeight: "400",
    lineHeight: 1.55,
    letterSpacing: 0.4,
    headingCase: "none",
    radius: 14,
    radiusSm: 8,
    borderWidth: 1,
    shadowIntensity: "strong",
    containerWidth: 1280,
    sectionGap: 64,
    gridGap: 16,
    cardStyle: "raised",
    buttonStyle: "solid",
    inputStyle: "outlined",
    imageRatio: "3/4",
    plpColumns: 4,
    intensity: "cinematic",
    pageTransition: "fade",
    hoverLift: true,
    parallax: true,
    confetti: true,
    backgroundFx: "none",
    scrollReveal: true,
    duration: 1,
  },
}
