export default {
  id: "forest-floor",
  name: "Forest Floor",
  description: "Deep woods — moss greens and firefly gold on forest night.",
  tags: ["dark","nature","green"],
  preview: {"bg":"#0E1A12","a":"#34D399","b":"#A3E635","c":"#FBBF24"},
  tokens: {
    primary: "#34D399",
    primaryFg: "#0E1A12",
    secondary: "#A3E635",
    accent: "#FBBF24",
    bg: "#0E1A12",
    surface: "#152419",
    surfaceAlt: "#122015",
    text: "#E9F5EC",
    textMuted: "#8FA898",
    border: "#24382A",
    success: "#10B981",
    warning: "#F59E0B",
    danger: "#EF4444",
    info: "#3B82F6",
    fontHeading: "'Inter', system-ui, sans-serif",
    fontBody: "'Inter', system-ui, sans-serif",
    baseSize: 15,
    scaleRatio: 1.25,
    headingWeight: "700",
    bodyWeight: "400",
    lineHeight: 1.55,
    letterSpacing: 0,
    headingCase: "none",
    radius: 14,
    radiusSm: 8,
    borderWidth: 1,
    shadowIntensity: "medium",
    containerWidth: 1280,
    sectionGap: 64,
    gridGap: 16,
    cardStyle: "raised",
    buttonStyle: "solid",
    inputStyle: "outlined",
    imageRatio: "16/9",
    plpColumns: 4,
    intensity: "subtle",
    pageTransition: "fade",
    hoverLift: true,
    parallax: true,
    confetti: false,
    backgroundFx: "noise",
    scrollReveal: true,
    duration: 1,
  },
}
