export default {
  id: "fresh-market",
  name: "Fresh Market",
  description: "Farm-fresh grocery — leaf green, harvest orange, square honest cards.",
  tags: ["grocery","food","green","fresh"],
  preview: {"bg":"#F7FEF0","a":"#16A34A","b":"#65A30D","c":"#F97316"},
  tokens: {
    primary: "#16A34A",
    primaryFg: "#FFFFFF",
    secondary: "#65A30D",
    accent: "#F97316",
    bg: "#F7FEF0",
    surface: "#FFFFFF",
    surfaceAlt: "#EFF9E4",
    text: "#1A2E14",
    textMuted: "#6B8A5E",
    border: "#D3E8C3",
    success: "#10B981",
    warning: "#F59E0B",
    danger: "#EF4444",
    info: "#3B82F6",
    fontHeading: "'Inter', system-ui, sans-serif",
    fontBody: "'Inter', system-ui, sans-serif",
    baseSize: 15,
    scaleRatio: 1.25,
    headingWeight: "800",
    bodyWeight: "400",
    lineHeight: 1.55,
    letterSpacing: 0,
    headingCase: "none",
    radius: 14,
    radiusSm: 8,
    borderWidth: 1,
    shadowIntensity: "soft",
    containerWidth: 1280,
    sectionGap: 64,
    gridGap: 16,
    cardStyle: "raised",
    buttonStyle: "solid",
    inputStyle: "outlined",
    imageRatio: "1/1",
    plpColumns: 5,
    intensity: "normal",
    pageTransition: "fade",
    hoverLift: true,
    parallax: true,
    confetti: false,
    backgroundFx: "none",
    scrollReveal: true,
    duration: 1,
  },
}
