export default {
  id: "frosted-mint",
  name: "Frosted Mint",
  description: "Cool mint glassmorphism — frosted cards over a fresh aqua gradient.",
  tags: ["light","glass","mint","fresh"],
  preview: {"bg":"#ECFDF5","a":"#0D9488","b":"#34D399","c":"#F472B6"},
  tokens: {
    primary: "#0D9488",
    primaryFg: "#FFFFFF",
    secondary: "#34D399",
    accent: "#F472B6",
    bg: "#ECFDF5",
    surface: "#FFFFFF",
    surfaceAlt: "#F0FDF9",
    text: "#0F2E2A",
    textMuted: "#5E8B84",
    border: "#C9EDE4",
    success: "#10B981",
    warning: "#F59E0B",
    danger: "#EF4444",
    info: "#3B82F6",
    fontHeading: "'Inter', system-ui, sans-serif",
    fontBody: "'Inter', system-ui, sans-serif",
    baseSize: 15,
    scaleRatio: 1.25,
    headingWeight: "700",
    bodyWeight: "400",
    lineHeight: 1.55,
    letterSpacing: -0.2,
    headingCase: "none",
    radius: 20,
    radiusSm: 12,
    borderWidth: 1,
    shadowIntensity: "soft",
    containerWidth: 1280,
    sectionGap: 64,
    gridGap: 16,
    cardStyle: "glass",
    buttonStyle: "solid",
    inputStyle: "outlined",
    imageRatio: "3/4",
    plpColumns: 4,
    intensity: "cinematic",
    pageTransition: "fade",
    hoverLift: true,
    parallax: true,
    confetti: false,
    backgroundFx: "aurora",
    scrollReveal: true,
    duration: 1,
  },
}
