export default {
  id: "glass-noir",
  name: "Glass Noir",
  description: "Dark frosted glass — smoky translucent panels with electric blue highlights.",
  tags: ["dark","glass","modern"],
  preview: {"bg":"#0B0F14","a":"#38BDF8","b":"#818CF8","c":"#F472B6"},
  tokens: {
    primary: "#38BDF8",
    primaryFg: "#0B0F14",
    secondary: "#818CF8",
    accent: "#F472B6",
    bg: "#0B0F14",
    surface: "#141B24",
    surfaceAlt: "#0F1620",
    text: "#F1F5F9",
    textMuted: "#94A3B8",
    border: "#243041",
    success: "#10B981",
    warning: "#F59E0B",
    danger: "#EF4444",
    info: "#3B82F6",
    fontHeading: "'Inter', system-ui, sans-serif",
    fontBody: "'Inter', system-ui, sans-serif",
    baseSize: 15,
    scaleRatio: 1.25,
    headingWeight: "800",
    bodyWeight: "400",
    lineHeight: 1.55,
    letterSpacing: -0.2,
    headingCase: "none",
    radius: 18,
    radiusSm: 10,
    borderWidth: 1,
    shadowIntensity: "strong",
    containerWidth: 1280,
    sectionGap: 64,
    gridGap: 16,
    cardStyle: "glass",
    buttonStyle: "solid",
    inputStyle: "outlined",
    imageRatio: "3/4",
    plpColumns: 4,
    intensity: "cinematic",
    pageTransition: "blur",
    hoverLift: true,
    parallax: true,
    confetti: false,
    backgroundFx: "mesh",
    scrollReveal: true,
    duration: 1,
  },
}
