export default {
  id: "holi-pop",
  name: "Holi Pop",
  description: "Colour-throw joy — gulal pink, violet and marigold in full play.",
  tags: ["festive","indian","playful","colourful"],
  preview: {"bg":"#FDF4FF","a":"#D946EF","b":"#3B82F6","c":"#EAB308"},
  tokens: {
    primary: "#D946EF",
    primaryFg: "#FFFFFF",
    secondary: "#3B82F6",
    accent: "#EAB308",
    bg: "#FDF4FF",
    surface: "#FFFFFF",
    surfaceAlt: "#F5E9FE",
    text: "#3B0A4A",
    textMuted: "#9A6FB0",
    border: "#E9C8F7",
    success: "#10B981",
    warning: "#F59E0B",
    danger: "#EF4444",
    info: "#3B82F6",
    fontHeading: "'Inter', system-ui, sans-serif",
    fontBody: "'Inter', system-ui, sans-serif",
    baseSize: 15,
    scaleRatio: 1.25,
    headingWeight: "800",
    bodyWeight: "400",
    lineHeight: 1.55,
    letterSpacing: 0,
    headingCase: "none",
    radius: 20,
    radiusSm: 12,
    borderWidth: 1,
    shadowIntensity: "medium",
    containerWidth: 1280,
    sectionGap: 64,
    gridGap: 16,
    cardStyle: "raised",
    buttonStyle: "pill",
    inputStyle: "outlined",
    imageRatio: "3/4",
    plpColumns: 4,
    intensity: "normal",
    pageTransition: "scale",
    hoverLift: true,
    parallax: true,
    confetti: true,
    backgroundFx: "mesh",
    scrollReveal: true,
    duration: 1,
  },
}
