export default {
  id: "ivory-bank",
  name: "Ivory Bank",
  description: "Private-banking polish — deep green and gold on ivory.",
  tags: ["light","corporate","finance","elegant"],
  preview: {"bg":"#FFFEF9","a":"#14532D","b":"#166534","c":"#B45309"},
  tokens: {
    primary: "#14532D",
    primaryFg: "#FFFFFF",
    secondary: "#166534",
    accent: "#B45309",
    bg: "#FFFEF9",
    surface: "#FFFFFF",
    surfaceAlt: "#F5F2E4",
    text: "#1A2E1F",
    textMuted: "#7A8A72",
    border: "#E2DCC4",
    success: "#10B981",
    warning: "#F59E0B",
    danger: "#EF4444",
    info: "#3B82F6",
    fontHeading: "'Playfair Display', Georgia, serif",
    fontBody: "'Inter', system-ui, sans-serif",
    baseSize: 15,
    scaleRatio: 1.25,
    headingWeight: "700",
    bodyWeight: "400",
    lineHeight: 1.55,
    letterSpacing: 0.3,
    headingCase: "none",
    radius: 4,
    radiusSm: 2,
    borderWidth: 1,
    shadowIntensity: "none",
    containerWidth: 1280,
    sectionGap: 96,
    gridGap: 16,
    cardStyle: "outlined",
    buttonStyle: "solid",
    inputStyle: "outlined",
    imageRatio: "3/4",
    plpColumns: 4,
    intensity: "off",
    pageTransition: "fade",
    hoverLift: true,
    parallax: true,
    confetti: false,
    backgroundFx: "none",
    scrollReveal: true,
    duration: 1,
  },
}
