export default {
  id: "lavender-mist",
  name: "Lavender Mist",
  description: "Dreamy lavender glass — soft violet haze with pill buttons.",
  tags: ["light","glass","purple","soft"],
  preview: {"bg":"#F5F3FF","a":"#8B5CF6","b":"#A78BFA","c":"#F472B6"},
  tokens: {
    primary: "#8B5CF6",
    primaryFg: "#FFFFFF",
    secondary: "#A78BFA",
    accent: "#F472B6",
    bg: "#F5F3FF",
    surface: "#FFFFFF",
    surfaceAlt: "#EDE9FE",
    text: "#2E2350",
    textMuted: "#8B83A8",
    border: "#DDD6FE",
    success: "#10B981",
    warning: "#F59E0B",
    danger: "#EF4444",
    info: "#3B82F6",
    fontHeading: "'Inter', system-ui, sans-serif",
    fontBody: "'Inter', system-ui, sans-serif",
    baseSize: 15,
    scaleRatio: 1.25,
    headingWeight: "600",
    bodyWeight: "400",
    lineHeight: 1.55,
    letterSpacing: 0,
    headingCase: "none",
    radius: 24,
    radiusSm: 14,
    borderWidth: 1,
    shadowIntensity: "soft",
    containerWidth: 1280,
    sectionGap: 64,
    gridGap: 16,
    cardStyle: "glass",
    buttonStyle: "pill",
    inputStyle: "outlined",
    imageRatio: "3/4",
    plpColumns: 4,
    intensity: "subtle",
    pageTransition: "fade",
    hoverLift: true,
    parallax: true,
    confetti: false,
    backgroundFx: "mesh",
    scrollReveal: true,
    duration: 1,
  },
}
