export default {
  id: "marigold-fest",
  name: "Marigold Fest",
  description: "Festive warmth — marigold, diya orange and celebratory confetti.",
  tags: ["festive","indian","orange"],
  preview: {"bg":"#FFF7ED","a":"#F59E0B","b":"#EA580C","c":"#DC2626"},
  tokens: {
    primary: "#F59E0B",
    primaryFg: "#451A03",
    secondary: "#EA580C",
    accent: "#DC2626",
    bg: "#FFF7ED",
    surface: "#FFFFFF",
    surfaceAlt: "#FFEDD5",
    text: "#431407",
    textMuted: "#B45309",
    border: "#FED7AA",
    success: "#10B981",
    warning: "#F59E0B",
    danger: "#EF4444",
    info: "#3B82F6",
    fontHeading: "'Inter', system-ui, sans-serif",
    fontBody: "'Inter', system-ui, sans-serif",
    baseSize: 15,
    scaleRatio: 1.25,
    headingWeight: "800",
    bodyWeight: "400",
    lineHeight: 1.55,
    letterSpacing: 0,
    headingCase: "none",
    radius: 18,
    radiusSm: 10,
    borderWidth: 1,
    shadowIntensity: "medium",
    containerWidth: 1280,
    sectionGap: 64,
    gridGap: 16,
    cardStyle: "raised",
    buttonStyle: "solid",
    inputStyle: "outlined",
    imageRatio: "3/4",
    plpColumns: 4,
    intensity: "normal",
    pageTransition: "scale",
    hoverLift: true,
    parallax: true,
    confetti: true,
    backgroundFx: "rangoli",
    scrollReveal: true,
    duration: 1,
  },
}
