export default {
  id: "matcha-zen",
  name: "Matcha Zen",
  description: "Wabi-sabi minimal — whisked matcha green on rice-paper white.",
  tags: ["light","nature","minimal","japanese"],
  preview: {"bg":"#F4F7EE","a":"#4D7C0F","b":"#84CC16","c":"#1C1917"},
  tokens: {
    primary: "#4D7C0F",
    primaryFg: "#FFFFFF",
    secondary: "#84CC16",
    accent: "#1C1917",
    bg: "#F4F7EE",
    surface: "#FBFDF7",
    surfaceAlt: "#E9F0DC",
    text: "#1F2A12",
    textMuted: "#7A8A64",
    border: "#D5DEBE",
    success: "#10B981",
    warning: "#F59E0B",
    danger: "#EF4444",
    info: "#3B82F6",
    fontHeading: "'Inter', system-ui, sans-serif",
    fontBody: "'Inter', system-ui, sans-serif",
    baseSize: 15,
    scaleRatio: 1.25,
    headingWeight: "600",
    bodyWeight: "400",
    lineHeight: 1.55,
    letterSpacing: 2,
    headingCase: "uppercase",
    radius: 4,
    radiusSm: 2,
    borderWidth: 1,
    shadowIntensity: "none",
    containerWidth: 1280,
    sectionGap: 112,
    gridGap: 24,
    cardStyle: "outlined",
    buttonStyle: "solid",
    inputStyle: "outlined",
    imageRatio: "3/4",
    plpColumns: 4,
    intensity: "off",
    pageTransition: "fade",
    hoverLift: true,
    parallax: true,
    confetti: false,
    backgroundFx: "none",
    scrollReveal: true,
    duration: 1,
  },
}
