export default {
  id: "midnight-emerald",
  name: "Midnight Emerald",
  description: "Jewel-toned luxury — deep emerald night with gold filigree accents.",
  tags: ["dark","luxury","green","jewellery"],
  preview: {"bg":"#06231B","a":"#34D399","b":"#10B981","c":"#D4AF37"},
  tokens: {
    primary: "#34D399",
    primaryFg: "#06231B",
    secondary: "#10B981",
    accent: "#D4AF37",
    bg: "#06231B",
    surface: "#0A2F24",
    surfaceAlt: "#083020",
    text: "#ECFDF5",
    textMuted: "#8FB3A4",
    border: "#1D4A3A",
    success: "#10B981",
    warning: "#F59E0B",
    danger: "#EF4444",
    info: "#3B82F6",
    fontHeading: "'Playfair Display', Georgia, serif",
    fontBody: "'Inter', system-ui, sans-serif",
    baseSize: 15,
    scaleRatio: 1.25,
    headingWeight: "800",
    bodyWeight: "400",
    lineHeight: 1.55,
    letterSpacing: 0,
    headingCase: "none",
    radius: 12,
    radiusSm: 6,
    borderWidth: 1,
    shadowIntensity: "strong",
    containerWidth: 1280,
    sectionGap: 64,
    gridGap: 16,
    cardStyle: "raised",
    buttonStyle: "solid",
    inputStyle: "outlined",
    imageRatio: "4/5",
    plpColumns: 3,
    intensity: "subtle",
    pageTransition: "fade",
    hoverLift: true,
    parallax: true,
    confetti: false,
    backgroundFx: "none",
    scrollReveal: true,
    duration: 1,
  },
}
