export default {
  id: "monsoon-mist",
  name: "Monsoon Mist",
  description: "Rain-washed calm — misty teal-grey with rain-blue glass.",
  tags: ["light","seasonal","calm","blue"],
  preview: {"bg":"#EFF6F6","a":"#0E7490","b":"#64748B","c":"#38BDF8"},
  tokens: {
    primary: "#0E7490",
    primaryFg: "#FFFFFF",
    secondary: "#64748B",
    accent: "#38BDF8",
    bg: "#EFF6F6",
    surface: "#F7FBFB",
    surfaceAlt: "#E2EDED",
    text: "#1E3238",
    textMuted: "#7A9299",
    border: "#C9DBDC",
    success: "#10B981",
    warning: "#F59E0B",
    danger: "#EF4444",
    info: "#3B82F6",
    fontHeading: "'Inter', system-ui, sans-serif",
    fontBody: "'Inter', system-ui, sans-serif",
    baseSize: 15,
    scaleRatio: 1.25,
    headingWeight: "600",
    bodyWeight: "400",
    lineHeight: 1.55,
    letterSpacing: -0.2,
    headingCase: "none",
    radius: 16,
    radiusSm: 10,
    borderWidth: 1,
    shadowIntensity: "soft",
    containerWidth: 1280,
    sectionGap: 64,
    gridGap: 16,
    cardStyle: "glass",
    buttonStyle: "solid",
    inputStyle: "outlined",
    imageRatio: "3/4",
    plpColumns: 4,
    intensity: "subtle",
    pageTransition: "fade",
    hoverLift: true,
    parallax: true,
    confetti: false,
    backgroundFx: "noise",
    scrollReveal: true,
    duration: 1.2,
  },
}
