export default {
  id: "muse-blush",
  name: "Muse Blush",
  description: "Soft editorial romance — blush pink, wine accents, graceful serifs.",
  tags: ["light","fashion","pink"],
  preview: {"bg":"#FDF2F4","a":"#BE123C","b":"#F472B6","c":"#FBBF24"},
  tokens: {
    primary: "#BE123C",
    primaryFg: "#FFFFFF",
    secondary: "#F472B6",
    accent: "#FBBF24",
    bg: "#FDF2F4",
    surface: "#FFFFFF",
    surfaceAlt: "#FCE7EB",
    text: "#3F1D28",
    textMuted: "#A67E88",
    border: "#F6D3DC",
    success: "#10B981",
    warning: "#F59E0B",
    danger: "#EF4444",
    info: "#3B82F6",
    fontHeading: "'Playfair Display', Georgia, serif",
    fontBody: "'Inter', system-ui, sans-serif",
    baseSize: 15,
    scaleRatio: 1.25,
    headingWeight: "600",
    bodyWeight: "400",
    lineHeight: 1.55,
    letterSpacing: 0.2,
    headingCase: "capitalize",
    radius: 20,
    radiusSm: 12,
    borderWidth: 1,
    shadowIntensity: "soft",
    containerWidth: 1280,
    sectionGap: 64,
    gridGap: 16,
    cardStyle: "raised",
    buttonStyle: "pill",
    inputStyle: "outlined",
    imageRatio: "4/5",
    plpColumns: 3,
    intensity: "subtle",
    pageTransition: "fade",
    hoverLift: true,
    parallax: true,
    confetti: false,
    backgroundFx: "none",
    scrollReveal: true,
    duration: 1,
  },
}
