export default {
  id: "neon-terminal",
  name: "Neon Terminal",
  description: "Hacker chic — phosphor green on black with scanline calm.",
  tags: ["dark","tech","neon","terminal"],
  preview: {"bg":"#050807","a":"#00FF87","b":"#00E5FF","c":"#FACC15"},
  tokens: {
    primary: "#00FF87",
    primaryFg: "#050807",
    secondary: "#00E5FF",
    accent: "#FACC15",
    bg: "#050807",
    surface: "#0A0F0C",
    surfaceAlt: "#080C0A",
    text: "#D1FAE5",
    textMuted: "#5E8A72",
    border: "#16301F",
    success: "#10B981",
    warning: "#F59E0B",
    danger: "#EF4444",
    info: "#3B82F6",
    fontHeading: "'JetBrains Mono', monospace",
    fontBody: "'JetBrains Mono', monospace",
    baseSize: 14,
    scaleRatio: 1.25,
    headingWeight: "700",
    bodyWeight: "400",
    lineHeight: 1.55,
    letterSpacing: 0,
    headingCase: "none",
    radius: 4,
    radiusSm: 2,
    borderWidth: 1,
    shadowIntensity: "none",
    containerWidth: 1280,
    sectionGap: 64,
    gridGap: 16,
    cardStyle: "flat",
    buttonStyle: "outline",
    inputStyle: "underline",
    imageRatio: "3/4",
    plpColumns: 4,
    intensity: "subtle",
    pageTransition: "none",
    hoverLift: true,
    parallax: true,
    confetti: false,
    backgroundFx: "grid",
    scrollReveal: true,
    duration: 1,
  },
}
