export default {
  id: "onyx-gold",
  name: "Onyx & Gold",
  description: "Dark luxury — polished onyx with rich gold accents and cinematic stillness.",
  tags: ["dark","luxury","gold"],
  preview: {"bg":"#0A0A0B","a":"#D4AF37","b":"#B08D57","c":"#F59E0B"},
  tokens: {
    primary: "#D4AF37",
    primaryFg: "#0A0A0B",
    secondary: "#B08D57",
    accent: "#F59E0B",
    bg: "#0A0A0B",
    surface: "#141414",
    surfaceAlt: "#1A1A1A",
    text: "#F5F0E6",
    textMuted: "#A89E8C",
    border: "#2E2A22",
    success: "#10B981",
    warning: "#F59E0B",
    danger: "#EF4444",
    info: "#3B82F6",
    fontHeading: "'Playfair Display', Georgia, serif",
    fontBody: "'Inter', system-ui, sans-serif",
    baseSize: 15,
    scaleRatio: 1.25,
    headingWeight: "800",
    bodyWeight: "400",
    lineHeight: 1.55,
    letterSpacing: 0.5,
    headingCase: "none",
    radius: 10,
    radiusSm: 6,
    borderWidth: 1,
    shadowIntensity: "strong",
    containerWidth: 1280,
    sectionGap: 64,
    gridGap: 16,
    cardStyle: "raised",
    buttonStyle: "solid",
    inputStyle: "outlined",
    imageRatio: "4/5",
    plpColumns: 3,
    intensity: "subtle",
    pageTransition: "fade",
    hoverLift: false,
    parallax: false,
    confetti: false,
    backgroundFx: "none",
    scrollReveal: true,
    duration: 1,
  },
}
