export default {
  id: "paper-ink",
  name: "Paper & Ink",
  description: "Editorial paper — warm stock, ink blacks, a single red seal.",
  tags: ["light","minimal","editorial"],
  preview: {"bg":"#F5F1E8","a":"#1C1917","b":"#57534E","c":"#DC2626"},
  tokens: {
    primary: "#1C1917",
    primaryFg: "#FFFFFF",
    secondary: "#57534E",
    accent: "#DC2626",
    bg: "#F5F1E8",
    surface: "#FBF8F1",
    surfaceAlt: "#EFE9DB",
    text: "#1C1917",
    textMuted: "#78716C",
    border: "#DDD3C0",
    success: "#10B981",
    warning: "#F59E0B",
    danger: "#EF4444",
    info: "#3B82F6",
    fontHeading: "Georgia, 'Times New Roman', serif",
    fontBody: "'Inter', system-ui, sans-serif",
    baseSize: 15,
    scaleRatio: 1.25,
    headingWeight: "700",
    bodyWeight: "400",
    lineHeight: 1.55,
    letterSpacing: 0.2,
    headingCase: "none",
    radius: 4,
    radiusSm: 2,
    borderWidth: 1,
    shadowIntensity: "none",
    containerWidth: 1280,
    sectionGap: 64,
    gridGap: 16,
    cardStyle: "outlined",
    buttonStyle: "solid",
    inputStyle: "outlined",
    imageRatio: "4/5",
    plpColumns: 4,
    intensity: "off",
    pageTransition: "fade",
    hoverLift: true,
    parallax: true,
    confetti: false,
    backgroundFx: "noise",
    scrollReveal: true,
    duration: 1,
  },
}
