export default {
  id: "peacock-pride",
  name: "Peacock Pride",
  description: "Iridescent pride — peacock teal, royal blue and a gold eye.",
  tags: ["indian","colourful","peacock"],
  preview: {"bg":"#ECFEFF","a":"#0F766E","b":"#1E40AF","c":"#CA8A04"},
  tokens: {
    primary: "#0F766E",
    primaryFg: "#FFFFFF",
    secondary: "#1E40AF",
    accent: "#CA8A04",
    bg: "#ECFEFF",
    surface: "#FFFFFF",
    surfaceAlt: "#DFF7F5",
    text: "#083B38",
    textMuted: "#5E8A88",
    border: "#A8E0DA",
    success: "#10B981",
    warning: "#F59E0B",
    danger: "#EF4444",
    info: "#3B82F6",
    fontHeading: "'Inter', system-ui, sans-serif",
    fontBody: "'Inter', system-ui, sans-serif",
    baseSize: 15,
    scaleRatio: 1.25,
    headingWeight: "800",
    bodyWeight: "400",
    lineHeight: 1.55,
    letterSpacing: 0,
    headingCase: "none",
    radius: 20,
    radiusSm: 12,
    borderWidth: 1,
    shadowIntensity: "medium",
    containerWidth: 1280,
    sectionGap: 64,
    gridGap: 16,
    cardStyle: "raised",
    buttonStyle: "pill",
    inputStyle: "outlined",
    imageRatio: "3/4",
    plpColumns: 4,
    intensity: "normal",
    pageTransition: "fade",
    hoverLift: true,
    parallax: true,
    confetti: false,
    backgroundFx: "mesh",
    scrollReveal: true,
    duration: 1,
  },
}
