export default {
  id: "porcelain",
  name: "Porcelain",
  description: "Ultra-minimal white — quiet surfaces, hairline borders, zero noise.",
  tags: ["light","minimal","white"],
  preview: {"bg":"#FAFAF9","a":"#334155","b":"#94A3B8","c":"#C2410C"},
  tokens: {
    primary: "#334155",
    primaryFg: "#FFFFFF",
    secondary: "#94A3B8",
    accent: "#C2410C",
    bg: "#FAFAF9",
    surface: "#FFFFFF",
    surfaceAlt: "#F5F5F4",
    text: "#1C1917",
    textMuted: "#A8A29E",
    border: "#E7E5E4",
    success: "#10B981",
    warning: "#F59E0B",
    danger: "#EF4444",
    info: "#3B82F6",
    fontHeading: "'Inter', system-ui, sans-serif",
    fontBody: "'Inter', system-ui, sans-serif",
    baseSize: 15,
    scaleRatio: 1.25,
    headingWeight: "600",
    bodyWeight: "400",
    lineHeight: 1.55,
    letterSpacing: -0.3,
    headingCase: "none",
    radius: 8,
    radiusSm: 4,
    borderWidth: 1,
    shadowIntensity: "none",
    containerWidth: 1280,
    sectionGap: 96,
    gridGap: 24,
    cardStyle: "flat",
    buttonStyle: "solid",
    inputStyle: "outlined",
    imageRatio: "3/4",
    plpColumns: 4,
    intensity: "off",
    pageTransition: "none",
    hoverLift: false,
    parallax: false,
    confetti: false,
    backgroundFx: "none",
    scrollReveal: false,
    duration: 1,
  },
}
