export default {
  id: "retro-diner",
  name: "Retro Diner",
  description: "Fifties soda-shop — cherry red, diner teal and mustard cream.",
  tags: ["retro","playful","diner"],
  preview: {"bg":"#FFF8F0","a":"#DC2626","b":"#0EA5E9","c":"#FBBF24"},
  tokens: {
    primary: "#DC2626",
    primaryFg: "#FFFFFF",
    secondary: "#0EA5E9",
    accent: "#FBBF24",
    bg: "#FFF8F0",
    surface: "#FFFFFF",
    surfaceAlt: "#FDEBD3",
    text: "#3B1F16",
    textMuted: "#A08062",
    border: "#F0D3AC",
    success: "#10B981",
    warning: "#F59E0B",
    danger: "#EF4444",
    info: "#3B82F6",
    fontHeading: "'Poppins', 'Inter', system-ui, sans-serif",
    fontBody: "'Inter', system-ui, sans-serif",
    baseSize: 15,
    scaleRatio: 1.25,
    headingWeight: "800",
    bodyWeight: "400",
    lineHeight: 1.55,
    letterSpacing: 1,
    headingCase: "uppercase",
    radius: 16,
    radiusSm: 10,
    borderWidth: 1,
    shadowIntensity: "medium",
    containerWidth: 1280,
    sectionGap: 64,
    gridGap: 16,
    cardStyle: "raised",
    buttonStyle: "pill",
    inputStyle: "outlined",
    imageRatio: "3/4",
    plpColumns: 4,
    intensity: "normal",
    pageTransition: "slide",
    hoverLift: true,
    parallax: true,
    confetti: true,
    backgroundFx: "none",
    scrollReveal: true,
    duration: 1,
  },
}
