export default {
  id: "rose-gold-blush",
  name: "Rose Gold Blush",
  description: "Modern heirloom — rose gold shimmer in frosted blush glass.",
  tags: ["light","jewellery","pink","glass"],
  preview: {"bg":"#FFF5F3","a":"#B76E79","b":"#E8B4B8","c":"#8C5E58"},
  tokens: {
    primary: "#B76E79",
    primaryFg: "#FFFFFF",
    secondary: "#E8B4B8",
    accent: "#8C5E58",
    bg: "#FFF5F3",
    surface: "#FFFDFC",
    surfaceAlt: "#F9E8E4",
    text: "#3A2422",
    textMuted: "#A07E78",
    border: "#F0D5CE",
    success: "#10B981",
    warning: "#F59E0B",
    danger: "#EF4444",
    info: "#3B82F6",
    fontHeading: "'Playfair Display', Georgia, serif",
    fontBody: "'Inter', system-ui, sans-serif",
    baseSize: 15,
    scaleRatio: 1.25,
    headingWeight: "600",
    bodyWeight: "400",
    lineHeight: 1.55,
    letterSpacing: 0,
    headingCase: "none",
    radius: 20,
    radiusSm: 12,
    borderWidth: 1,
    shadowIntensity: "soft",
    containerWidth: 1280,
    sectionGap: 64,
    gridGap: 16,
    cardStyle: "glass",
    buttonStyle: "solid",
    inputStyle: "outlined",
    imageRatio: "1/1",
    plpColumns: 3,
    intensity: "normal",
    pageTransition: "fade",
    hoverLift: true,
    parallax: true,
    confetti: false,
    backgroundFx: "aurora",
    scrollReveal: true,
    duration: 1,
  },
}
