export default {
  id: "royal-kundan",
  name: "Royal Kundan",
  description: "Maharaja opulence — gold, ruby and emerald on lacquered night.",
  tags: ["dark","jewellery","luxury","indian"],
  preview: {"bg":"#160B08","a":"#D4AF37","b":"#B91C1C","c":"#0F766E"},
  tokens: {
    primary: "#D4AF37",
    primaryFg: "#160B08",
    secondary: "#B91C1C",
    accent: "#0F766E",
    bg: "#160B08",
    surface: "#221009",
    surfaceAlt: "#1E0D08",
    text: "#F8F1E5",
    textMuted: "#BFA98E",
    border: "#3E2417",
    success: "#10B981",
    warning: "#F59E0B",
    danger: "#EF4444",
    info: "#3B82F6",
    fontHeading: "'Playfair Display', Georgia, serif",
    fontBody: "'Inter', system-ui, sans-serif",
    baseSize: 15,
    scaleRatio: 1.25,
    headingWeight: "800",
    bodyWeight: "400",
    lineHeight: 1.55,
    letterSpacing: 1.5,
    headingCase: "uppercase",
    radius: 8,
    radiusSm: 4,
    borderWidth: 1,
    shadowIntensity: "strong",
    containerWidth: 1280,
    sectionGap: 64,
    gridGap: 16,
    cardStyle: "raised",
    buttonStyle: "solid",
    inputStyle: "outlined",
    imageRatio: "1/1",
    plpColumns: 3,
    intensity: "subtle",
    pageTransition: "fade",
    hoverLift: true,
    parallax: true,
    confetti: false,
    backgroundFx: "none",
    scrollReveal: true,
    duration: 1,
  },
}
