export default {
  id: "runway-noir",
  name: "Runway Noir",
  description: "Fashion editorial — stark black, loud red, oversized uppercase type.",
  tags: ["dark","fashion","editorial"],
  preview: {"bg":"#0B0B0C","a":"#F5F5F5","b":"#E11D48","c":"#E11D48"},
  tokens: {
    primary: "#F5F5F5",
    primaryFg: "#0B0B0C",
    secondary: "#E11D48",
    accent: "#E11D48",
    bg: "#0B0B0C",
    surface: "#141414",
    surfaceAlt: "#101010",
    text: "#FAFAFA",
    textMuted: "#A1A1AA",
    border: "#262626",
    success: "#10B981",
    warning: "#F59E0B",
    danger: "#EF4444",
    info: "#3B82F6",
    fontHeading: "'Poppins', 'Inter', system-ui, sans-serif",
    fontBody: "'Poppins', 'Inter', system-ui, sans-serif",
    baseSize: 15,
    scaleRatio: 1.25,
    headingWeight: "900",
    bodyWeight: "300",
    lineHeight: 1.55,
    letterSpacing: 1.5,
    headingCase: "uppercase",
    radius: 0,
    radiusSm: 0,
    borderWidth: 1,
    shadowIntensity: "none",
    containerWidth: 1280,
    sectionGap: 64,
    gridGap: 16,
    cardStyle: "flat",
    buttonStyle: "solid",
    inputStyle: "outlined",
    imageRatio: "4/5",
    plpColumns: 3,
    intensity: "normal",
    pageTransition: "slide",
    hoverLift: true,
    parallax: true,
    confetti: false,
    backgroundFx: "none",
    scrollReveal: true,
    duration: 1,
  },
}
