export default {
  id: "slate-executive",
  name: "Slate Executive",
  description: "After-hours authority — deep slate with electric blue edge.",
  tags: ["dark","corporate","blue"],
  preview: {"bg":"#0F172A","a":"#38BDF8","b":"#818CF8","c":"#F59E0B"},
  tokens: {
    primary: "#38BDF8",
    primaryFg: "#0F172A",
    secondary: "#818CF8",
    accent: "#F59E0B",
    bg: "#0F172A",
    surface: "#16213A",
    surfaceAlt: "#131D33",
    text: "#F1F5F9",
    textMuted: "#8CA0B8",
    border: "#263349",
    success: "#10B981",
    warning: "#F59E0B",
    danger: "#EF4444",
    info: "#3B82F6",
    fontHeading: "'Inter', system-ui, sans-serif",
    fontBody: "'Inter', system-ui, sans-serif",
    baseSize: 15,
    scaleRatio: 1.25,
    headingWeight: "700",
    bodyWeight: "400",
    lineHeight: 1.55,
    letterSpacing: 0.3,
    headingCase: "none",
    radius: 10,
    radiusSm: 6,
    borderWidth: 1,
    shadowIntensity: "medium",
    containerWidth: 1280,
    sectionGap: 64,
    gridGap: 16,
    cardStyle: "raised",
    buttonStyle: "solid",
    inputStyle: "outlined",
    imageRatio: "3/4",
    plpColumns: 4,
    intensity: "subtle",
    pageTransition: "fade",
    hoverLift: true,
    parallax: true,
    confetti: false,
    backgroundFx: "grid",
    scrollReveal: true,
    duration: 1,
  },
}
