export default {
  id: "spice-route",
  name: "Spice Route",
  description: "Masala-dark marketplace — turmeric gold, chilli red on roasted umber.",
  tags: ["dark","food","spices","indian"],
  preview: {"bg":"#1F1409","a":"#F59E0B","b":"#DC2626","c":"#65A30D"},
  tokens: {
    primary: "#F59E0B",
    primaryFg: "#1F1409",
    secondary: "#DC2626",
    accent: "#65A30D",
    bg: "#1F1409",
    surface: "#2B1D0C",
    surfaceAlt: "#261809",
    text: "#FEF3C7",
    textMuted: "#C2A878",
    border: "#4A3317",
    success: "#10B981",
    warning: "#F59E0B",
    danger: "#EF4444",
    info: "#3B82F6",
    fontHeading: "Georgia, 'Times New Roman', serif",
    fontBody: "'Inter', system-ui, sans-serif",
    baseSize: 15,
    scaleRatio: 1.25,
    headingWeight: "700",
    bodyWeight: "400",
    lineHeight: 1.55,
    letterSpacing: 0,
    headingCase: "none",
    radius: 12,
    radiusSm: 8,
    borderWidth: 1,
    shadowIntensity: "strong",
    containerWidth: 1280,
    sectionGap: 64,
    gridGap: 16,
    cardStyle: "raised",
    buttonStyle: "solid",
    inputStyle: "outlined",
    imageRatio: "1/1",
    plpColumns: 4,
    intensity: "normal",
    pageTransition: "fade",
    hoverLift: true,
    parallax: true,
    confetti: false,
    backgroundFx: "noise",
    scrollReveal: true,
    duration: 1,
  },
}
