export default {
  id: "steel-trust",
  name: "Steel Trust",
  description: "Boardroom confidence — steel blue precision on cool grey.",
  tags: ["corporate","blue","trust"],
  preview: {"bg":"#F1F5F9","a":"#1D4ED8","b":"#0EA5E9","c":"#10B981"},
  tokens: {
    primary: "#1D4ED8",
    primaryFg: "#FFFFFF",
    secondary: "#0EA5E9",
    accent: "#10B981",
    bg: "#F1F5F9",
    surface: "#FFFFFF",
    surfaceAlt: "#E8EEF5",
    text: "#0F1E33",
    textMuted: "#64748B",
    border: "#D4DCE6",
    success: "#10B981",
    warning: "#F59E0B",
    danger: "#EF4444",
    info: "#3B82F6",
    fontHeading: "'Inter', system-ui, sans-serif",
    fontBody: "'Inter', system-ui, sans-serif",
    baseSize: 15,
    scaleRatio: 1.25,
    headingWeight: "700",
    bodyWeight: "400",
    lineHeight: 1.55,
    letterSpacing: 0,
    headingCase: "none",
    radius: 8,
    radiusSm: 4,
    borderWidth: 1,
    shadowIntensity: "soft",
    containerWidth: 1280,
    sectionGap: 64,
    gridGap: 16,
    cardStyle: "raised",
    buttonStyle: "solid",
    inputStyle: "outlined",
    imageRatio: "3/4",
    plpColumns: 4,
    intensity: "subtle",
    pageTransition: "fade",
    hoverLift: true,
    parallax: true,
    confetti: false,
    backgroundFx: "none",
    scrollReveal: true,
    duration: 1,
  },
}
