export default {
  id: "synthwave-84",
  name: "Synthwave 84",
  description: "Retro-future arcade — neon pink and cyan over midnight grid.",
  tags: ["dark","retro","neon"],
  preview: {"bg":"#0D0221","a":"#FF2FB3","b":"#22D3EE","c":"#FACC15"},
  tokens: {
    primary: "#FF2FB3",
    primaryFg: "#FFFFFF",
    secondary: "#22D3EE",
    accent: "#FACC15",
    bg: "#0D0221",
    surface: "#1A0B2E",
    surfaceAlt: "#150826",
    text: "#F5F3FF",
    textMuted: "#A79BC9",
    border: "#3B1D5E",
    success: "#10B981",
    warning: "#F59E0B",
    danger: "#EF4444",
    info: "#3B82F6",
    fontHeading: "'JetBrains Mono', monospace",
    fontBody: "'JetBrains Mono', monospace",
    baseSize: 15,
    scaleRatio: 1.25,
    headingWeight: "800",
    bodyWeight: "400",
    lineHeight: 1.55,
    letterSpacing: 1,
    headingCase: "none",
    radius: 4,
    radiusSm: 2,
    borderWidth: 1,
    shadowIntensity: "none",
    containerWidth: 1280,
    sectionGap: 64,
    gridGap: 16,
    cardStyle: "flat",
    buttonStyle: "outline",
    inputStyle: "filled",
    imageRatio: "3/4",
    plpColumns: 4,
    intensity: "cinematic",
    pageTransition: "blur",
    hoverLift: true,
    parallax: true,
    confetti: false,
    backgroundFx: "grid",
    scrollReveal: true,
    duration: 1,
  },
}
