export default {
  id: "terracotta-craft",
  name: "Terracotta Craft",
  description: "Handmade earth — kiln-fired terracotta on warm clay.",
  tags: ["indian","craft","earthy"],
  preview: {"bg":"#FBF3EC","a":"#C2410C","b":"#92400E","c":"#65A30D"},
  tokens: {
    primary: "#C2410C",
    primaryFg: "#FFFFFF",
    secondary: "#92400E",
    accent: "#65A30D",
    bg: "#FBF3EC",
    surface: "#FFF9F2",
    surfaceAlt: "#F3E7D7",
    text: "#3A2317",
    textMuted: "#9C7B5E",
    border: "#E7D3BC",
    success: "#10B981",
    warning: "#F59E0B",
    danger: "#EF4444",
    info: "#3B82F6",
    fontHeading: "Georgia, 'Times New Roman', serif",
    fontBody: "'Inter', system-ui, sans-serif",
    baseSize: 15,
    scaleRatio: 1.25,
    headingWeight: "700",
    bodyWeight: "400",
    lineHeight: 1.55,
    letterSpacing: 0,
    headingCase: "none",
    radius: 14,
    radiusSm: 8,
    borderWidth: 1,
    shadowIntensity: "medium",
    containerWidth: 1280,
    sectionGap: 64,
    gridGap: 16,
    cardStyle: "raised",
    buttonStyle: "solid",
    inputStyle: "outlined",
    imageRatio: "3/4",
    plpColumns: 4,
    intensity: "subtle",
    pageTransition: "fade",
    hoverLift: true,
    parallax: true,
    confetti: false,
    backgroundFx: "noise",
    scrollReveal: true,
    duration: 1,
  },
}
