export default {
  id: "toybox",
  name: "Toybox",
  description: "Primary-colour play — toy red, blue and green blocks of joy.",
  tags: ["kids","playful","colourful"],
  preview: {"bg":"#F0F9FF","a":"#3B82F6","b":"#EF4444","c":"#22C55E"},
  tokens: {
    primary: "#3B82F6",
    primaryFg: "#FFFFFF",
    secondary: "#EF4444",
    accent: "#22C55E",
    bg: "#F0F9FF",
    surface: "#FFFFFF",
    surfaceAlt: "#DBEAFE",
    text: "#0F2A4A",
    textMuted: "#7A93B5",
    border: "#BFD9F7",
    success: "#10B981",
    warning: "#F59E0B",
    danger: "#EF4444",
    info: "#3B82F6",
    fontHeading: "'Poppins', 'Inter', system-ui, sans-serif",
    fontBody: "'Poppins', 'Inter', system-ui, sans-serif",
    baseSize: 15,
    scaleRatio: 1.25,
    headingWeight: "800",
    bodyWeight: "400",
    lineHeight: 1.55,
    letterSpacing: 0,
    headingCase: "none",
    radius: 20,
    radiusSm: 12,
    borderWidth: 1,
    shadowIntensity: "medium",
    containerWidth: 1280,
    sectionGap: 64,
    gridGap: 16,
    cardStyle: "raised",
    buttonStyle: "pill",
    inputStyle: "outlined",
    imageRatio: "1/1",
    plpColumns: 4,
    intensity: "normal",
    pageTransition: "scale",
    hoverLift: true,
    parallax: true,
    confetti: true,
    backgroundFx: "none",
    scrollReveal: true,
    duration: 1,
  },
}
