export default {
  id: "velvet-noir",
  name: "Velvet Noir",
  description: "Plum-black opulence — velvet shadows with rose-gold glow.",
  tags: ["dark","luxury","plum"],
  preview: {"bg":"#120E17","a":"#B76E79","b":"#7C3AED","c":"#F59E0B"},
  tokens: {
    primary: "#B76E79",
    primaryFg: "#FFFFFF",
    secondary: "#7C3AED",
    accent: "#F59E0B",
    bg: "#120E17",
    surface: "#1C1626",
    surfaceAlt: "#181220",
    text: "#F7F2F7",
    textMuted: "#A79BB5",
    border: "#322A42",
    success: "#10B981",
    warning: "#F59E0B",
    danger: "#EF4444",
    info: "#3B82F6",
    fontHeading: "'Playfair Display', Georgia, serif",
    fontBody: "'Inter', system-ui, sans-serif",
    baseSize: 15,
    scaleRatio: 1.25,
    headingWeight: "700",
    bodyWeight: "400",
    lineHeight: 1.55,
    letterSpacing: 0.3,
    headingCase: "none",
    radius: 14,
    radiusSm: 8,
    borderWidth: 1,
    shadowIntensity: "strong",
    containerWidth: 1280,
    sectionGap: 64,
    gridGap: 16,
    cardStyle: "raised",
    buttonStyle: "solid",
    inputStyle: "outlined",
    imageRatio: "3/4",
    plpColumns: 4,
    intensity: "normal",
    pageTransition: "fade",
    hoverLift: true,
    parallax: true,
    confetti: false,
    backgroundFx: "mesh",
    scrollReveal: true,
    duration: 1,
  },
}
