export default {
  id: "vogue-contrast",
  name: "Vogue Contrast",
  description: "High-fashion shock — brutal black and white with a red slash.",
  tags: ["fashion","bold","contrast"],
  preview: {"bg":"#FFFFFF","a":"#000000","b":"#DC2626","c":"#DC2626"},
  tokens: {
    primary: "#000000",
    primaryFg: "#FFFFFF",
    secondary: "#DC2626",
    accent: "#DC2626",
    bg: "#FFFFFF",
    surface: "#FFFFFF",
    surfaceAlt: "#F5F5F5",
    text: "#000000",
    textMuted: "#525252",
    border: "#000000",
    success: "#10B981",
    warning: "#F59E0B",
    danger: "#EF4444",
    info: "#3B82F6",
    fontHeading: "'Poppins', 'Inter', system-ui, sans-serif",
    fontBody: "'Inter', system-ui, sans-serif",
    baseSize: 15,
    scaleRatio: 1.25,
    headingWeight: "900",
    bodyWeight: "400",
    lineHeight: 1.55,
    letterSpacing: 2,
    headingCase: "uppercase",
    radius: 0,
    radiusSm: 0,
    borderWidth: 2,
    shadowIntensity: "brutal",
    containerWidth: 1280,
    sectionGap: 64,
    gridGap: 16,
    cardStyle: "flat",
    buttonStyle: "solid",
    inputStyle: "outlined",
    imageRatio: "4/5",
    plpColumns: 3,
    intensity: "normal",
    pageTransition: "slide",
    hoverLift: true,
    parallax: true,
    confetti: false,
    backgroundFx: "none",
    scrollReveal: true,
    duration: 1,
  },
}
